// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using POS.Data;
using System;

namespace POS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180419060805_temp")]
    partial class temp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("POS.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("POS.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("C_City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("C_streetName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("C_streetNum")
                        .HasMaxLength(50);

                    b.Property<int>("C_zipCode");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MInit")
                        .HasMaxLength(50);

                    b.Property<int>("Phone_Number");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("POS.Models.Employee", b =>
                {
                    b.Property<int>("EmployerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("E_CityState")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("E_StreetName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("E_streetNum")
                        .HasMaxLength(50);

                    b.Property<int>("E_zipCode");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MInit")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("StoreID");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("EmployerID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("POS.Models.Inventory", b =>
                {
                    b.Property<int>("Inventory_PID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("I_productBrand")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("I_productModel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("I_productName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ProductPID");

                    b.Property<int>("ProductQTY");

                    b.Property<int>("Product_PID");

                    b.HasKey("Inventory_PID");

                    b.HasIndex("ProductPID");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("POS.Models.Product", b =>
                {
                    b.Property<int>("PID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("I_productBrand")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("I_productModel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("ProductCost");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("Sales_PID");

                    b.HasKey("PID");

                    b.HasIndex("Sales_PID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("POS.Models.Sales", b =>
                {
                    b.Property<int>("Sales_PID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerID");

                    b.Property<decimal>("DiscountPercentage");

                    b.Property<int>("EmployeeID");

                    b.Property<decimal>("OrderTotal");

                    b.Property<decimal>("RetailCost");

                    b.Property<string>("S_productBrand")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("S_productCost");

                    b.Property<string>("S_productModel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("S_productName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SalesUpdate");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("TransactionID");

                    b.HasKey("Sales_PID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("POS.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Store_City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Store_State")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Store_ZipCode");

                    b.Property<string>("Store_streetName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Store_streetNum");

                    b.HasKey("StoreID");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("POS.Models.Sup_Trans", b =>
                {
                    b.Property<int>("OrderNum")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Inventory_PID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SupplierUpdate");

                    b.Property<int>("Transaction_ID");

                    b.HasKey("OrderNum");

                    b.HasIndex("Inventory_PID");

                    b.ToTable("Sup_Trans");
                });

            modelBuilder.Entity("POS.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Order_Num");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("S_City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("S_State")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("S_streetName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("S_streetNum")
                        .HasMaxLength(50);

                    b.Property<int>("S_zipCode");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("SupplierID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("POS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("POS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("POS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("POS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("POS.Models.Inventory", b =>
                {
                    b.HasOne("POS.Models.Product")
                        .WithMany("GetInventories")
                        .HasForeignKey("ProductPID");
                });

            modelBuilder.Entity("POS.Models.Product", b =>
                {
                    b.HasOne("POS.Models.Sales")
                        .WithMany("GetProducts")
                        .HasForeignKey("Sales_PID");
                });

            modelBuilder.Entity("POS.Models.Sup_Trans", b =>
                {
                    b.HasOne("POS.Models.Inventory")
                        .WithMany("GetSup_Trans")
                        .HasForeignKey("Inventory_PID");
                });
#pragma warning restore 612, 618
        }
    }
}
